---
- hosts: all
  become: yes
  gather_facts: false
  ignore_errors: true
  tasks:
     - name: Check uptime
       command: uptime
       register: uptime_output
     - name: Create user
       user:
         name: ahriel 
         comment: Ahriel admin
       when: uptime_output.changed == "false"
     - name: Display output
       debug:
         var: uptime_output
     
